import type { Metadata } from 'next'
import { Poor_Story } from 'next/font/google'
import './globals.css'

//components
import { AuthContextProvider } from '@/context/AuthContext'

const inter = Poor_Story({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  
  return (    
      <html lang="en">      
        <body className={`${inter.className} text-lg`}>       
 
          {/* Wrap the children with the AuthContextProvider to provide authentication context */}
          <AuthContextProvider>                     
              {children}                               
          </AuthContextProvider>           
 
        </body>      
      </html>
    
    
  )
}
