import type { Metadata } from 'next'
import { Poor_Story } from 'next/font/google'
import './globals.css'
import { getAuthenticatedAppForUser } from '../../lib/firebase/serverApp'
import Header from '@/components/header/Header';

export const dynamic = "force-dynamic";

const inter = Poor_Story({ subsets: ['latin'], weight: '400' })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { currentUser } = await getAuthenticatedAppForUser();
  
  return (    
  <html lang="en">      
    <body className={`${inter.className}`}>
      <Header initialUser={currentUser?.toJSON()} />
      {children}
    </body>      
  </html>   
  )
}
