import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { getAuthenticatedAppForUser } from '../../../lib/firebase/firebase'

//components
import Navbar from '../components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: any) {
  const { currentUser }: any = await getAuthenticatedAppForUser();
return (
  <html lang="en">

        <body>
          <Navbar initialUser={currentUser?.toJSON()}/>
          <main>{children}</main>
        </body>

  </html>
);
}
